---
apiVersion: v1
kind: Namespace
metadata:
  name: config

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: totem
  namespace: config
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: totem
    spec:
      serviceAccount: totem
      containers:
        - name: totem
          image: quay.io/mad01/totem:{{VERSION}}
          command:
            - "totem"
          args:
            - "controller"
            - "--cluster.name=minikube"
            - "--cluster.addr=https://localhost:443"
            - "--token.lifetime=10m"
            - "--config=/config.yaml"
            - "--namespace=config"
            - "-v"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: totem-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: totem-config
  namespace: config
data:
  config.yaml: |
    ---
    users:
      - {name: alexander, clusterRole: admin, password: qwerty123}
      - {name: test, clusterRole: view, password: qwerty123}

---
apiVersion: v1
kind: Service
metadata:
  name: totem
  namespace: config
spec:
  selector:
    app: totem
  ports:
  - name: api
    protocol: TCP
    port: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: config
  name: totem

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: totem
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: totem
  namespace: config
