version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: build container
          command: |
            set -x
            VERSION="$(hacks/git-version)"
            docker build -t quay.io/mad01/totem:"${VERSION}" --file Dockerfile .

      - run:
          name: push container
          command: |
            set -x
            VERSION="$(hacks/git-version)"
            echo "${DOCKER_PASSWORD}" | docker login quay.io -u "${DOCKER_USERNAME}" --password-stdin ;
            docker push quay.io/mad01/totem:"${VERSION}"
